openapi: 3.0.3
info:
    title: Goa API
    version: 0.0.1
servers:
    - url: http://localhost:80
      description: Default server for mktextr
paths:
    /tasks/{taskId}/complete:
        patch:
            tags:
                - mktextr
            summary: completeTask mktextr
            operationId: mktextr#completeTask
            parameters:
                - name: taskId
                  in: path
                  description: ID of the task
                  required: true
                  schema:
                    type: string
                    description: ID of the task
                    example: Odio praesentium.
                  example: Nihil est ducimus in.
            requestBody:
                required: true
                content:
                    multipart/form-data:
                        schema:
                            $ref: '#/components/schemas/CompleteTaskRequestBody'
                        example:
                            file:
                                - 86
                                - 101
                                - 114
                                - 111
                                - 32
                                - 100
                                - 101
                                - 115
                                - 101
                                - 114
                                - 117
                                - 110
                                - 116
                                - 32
                                - 114
                                - 101
                                - 109
                                - 32
                                - 105
                                - 100
                                - 32
                                - 109
                                - 111
                                - 108
                                - 101
                                - 115
                                - 116
                                - 105
                                - 97
                                - 101
                                - 32
                                - 113
                                - 117
                                - 105
                                - 100
                                - 101
                                - 109
                                - 32
                                - 110
                                - 105
                                - 104
                                - 105
                                - 108
                                - 46
                            filename: Qui et.
            responses:
                "200":
                    description: OK response.
    /textures:
        get:
            tags:
                - mktextr
            summary: getTextureByCoordinates mktextr
            operationId: mktextr#getTextureByCoordinates
            parameters:
                - name: worldId
                  in: query
                  description: WorldId
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: string
                    description: WorldId
                    example: Rerum accusamus.
                  example: Doloribus quibusdam.
                - name: x
                  in: query
                  description: Texture X
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: integer
                    description: Texture X
                    example: 4748271283784381903
                    format: int64
                  example: 7523923742862776932
                - name: "y"
                  in: query
                  description: Texture Y
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: integer
                    description: Texture Y
                    example: 276245859482169956
                    format: int64
                  example: 3784236015956481100
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/MktextrGetTextureByCoordinatesOKResponseBody'
                            example:
                                baseMapUrl: Facere quibusdam.
                                contourMapUrl: Dolore voluptatem incidunt.
                                taskId: Molestiae nam est asperiores.
                "202":
                    description: Accepted response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/MktextrGetTextureByCoordinatesOKResponseBody'
                            example:
                                baseMapUrl: Facere quibusdam.
                                contourMapUrl: Dolore voluptatem incidunt.
                                taskId: Molestiae nam est asperiores.
                "400":
                    description: Bad Request response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/MktextrGetTextureByCoordinatesOKResponseBody'
                            example:
                                baseMapUrl: Facere quibusdam.
                                contourMapUrl: Dolore voluptatem incidunt.
                                taskId: Molestiae nam est asperiores.
    /textures/{id}:
        get:
            tags:
                - mktextr
            summary: getTextureById mktextr
            operationId: mktextr#getTextureById
            parameters:
                - name: id
                  in: path
                  description: Texture ID
                  required: true
                  schema:
                    type: string
                    description: Texture ID
                    example: Consequuntur quia assumenda.
                  example: Est eaque dolorum.
            responses:
                "204":
                    description: No Content response.
components:
    schemas:
        CompleteTaskRequestBody:
            type: object
            properties:
                file:
                    type: string
                    description: The file to upload
                    example:
                        - 69
                        - 116
                        - 32
                        - 100
                        - 111
                        - 108
                        - 111
                        - 114
                        - 105
                        - 98
                        - 117
                        - 115
                        - 32
                        - 117
                        - 116
                        - 32
                        - 105
                        - 112
                        - 115
                        - 97
                        - 32
                        - 101
                        - 116
                        - 32
                        - 101
                        - 116
                        - 32
                        - 97
                        - 117
                        - 116
                        - 46
                    format: binary
                filename:
                    type: string
                    description: Name of the file
                    example: Alias omnis et.
            example:
                file:
                    - 69
                    - 115
                    - 115
                    - 101
                    - 32
                    - 115
                    - 117
                    - 115
                    - 99
                    - 105
                    - 112
                    - 105
                    - 116
                    - 32
                    - 118
                    - 101
                    - 114
                    - 105
                    - 116
                    - 97
                    - 116
                    - 105
                    - 115
                    - 32
                    - 97
                    - 108
                    - 105
                    - 113
                    - 117
                    - 97
                    - 109
                    - 32
                    - 100
                    - 101
                    - 108
                    - 101
                    - 110
                    - 105
                    - 116
                    - 105
                    - 46
                filename: In quia pariatur.
            required:
                - file
                - filename
        GetResult:
            type: object
            properties:
                baseMapUrl:
                    type: string
                    example: Enim nihil.
                contourMapUrl:
                    type: string
                    example: Veniam error laudantium blanditiis vitae.
                status_code:
                    type: string
                    example: Sed dolor dolores.
                taskId:
                    type: string
                    example: Qui aliquid sapiente.
            description: Texture set payload
            example:
                baseMapUrl: Exercitationem dolor debitis nisi voluptatem aut perferendis.
                contourMapUrl: Corporis beatae vero qui voluptatem.
                status_code: Laborum excepturi in.
                taskId: Ab possimus quia molestias adipisci omnis.
        MktextrGetTextureByCoordinatesOKResponseBody:
            type: object
            properties:
                baseMapUrl:
                    type: string
                    example: Quos at.
                contourMapUrl:
                    type: string
                    example: Esse veniam omnis tempora sint non.
                taskId:
                    type: string
                    example: Voluptatem tenetur eius optio consequatur.
            description: GetTextureByCoordinatesOKResponseBody result type (default view)
            example:
                baseMapUrl: Voluptate reprehenderit assumenda unde eius dicta harum.
                contourMapUrl: Alias aspernatur fugiat sint.
                taskId: Dolorem similique non reprehenderit.
tags:
    - name: mktextr
      description: Texture store
